name: Publish to ghcr
on: [push]
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v8 --tag ghcr.io/ophelios-studio/docker-pulsar-postgres:latest .          
          docker push ghcr.io/ophelios-studio/docker-pulsar-postgres:latest